# Site Author
author:
  name             : "Your Name"
  name             : "Mark Kim"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an amazing person."
  location         : "Somewhere"
  bio              : "Learn more about DL since it's fun fun fun!"
  location         : "Seoul"
  email            :
  links:
    - label: "Email"
